### ISSUE TITLE
13 Styling Personal Info Items - Duplicate CSS

### ISSUE THREAD

**Issue by DaveyJH** [Code-Institute-Solutions/resume-miniproject-bootstrap4#2]
The following code is duplicated in style.css

``` css
.row-table {
  display: table;
}

.section-column {
  display: table-cell;
  padding: 0 30px 30px;
  float: none;
}

.section-heading {
  font-family: "Exo", sans-serif;
  font-weight: 300;
  margin-top: 25px;
  margin-bottom: 40px;
}
```

https://github.com/Code-Institute-Solutions/resume-miniproject-bootstrap4/blob/master/13-styling-personal-info-items/assets/css/style.css#L33-L48

https://github.com/Code-Institute-Solutions/resume-miniproject-bootstrap4/blob/master/13-styling-personal-info-items/assets/css/style.css#L73-L88
